apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: arc
  namespace: arc-runners
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Proptech/items/arc-operator"