apiVersion: v1
kind: Secret
metadata:
  name: atlas-credentials
  namespace: atlas-operator
type: Opaque
data:
  db_password:  {{ .Values.db_password | b64enc }}
  token:  {{ .Values.atlas_token | b64enc }}